name: Swift CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Swift 6.0.0
      run: |
        curl -O https://swift.org/builds/swift-6.0-release/xcode/swift-6.0-RELEASE/swift-6.0-RELEASE-osx.pkg
        sudo installer -pkg swift-6.0-RELEASE-osx.pkg -target /
    - name: Build and test
      run: swift build && swift test
