name: Swift CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: k-arindam/setup-swift@v6.0.0
      with:
        swift-version: "6.0.0" 
    - name: Build and test
      run: swift build && swift test
